Improve installation instructions and add contributing guide
Yoast/developer-site pull request #83
Opened 2020-11-20 14:27 UTC by JustinyAhin

This PR add details to installations intructions, and a contributing guide.

2020-11-20 14:40 UTC, JustinyAhin commented
Overall, do we need a specific CONTRIBUTING.md for the guidelines?

2020-11-20 14:48 UTC, moorscode commented on README.md
> +We use Jira to track changes and improvements to the portal that need to be discussed and completed. The portal related tickets are [in this board](#).
Jira isn't open for people outside of the company, so I guess the description needs to just ask for a GitHub issue on this repository.

2020-11-20 14:50 UTC, moorscode commented on README.md
> +### Reviewing pull requests
Not sure if you wanted to add information here, having a header without copy seems weird :)

2020-11-20 14:51 UTC, moorscode requested changes
Some small things that stand out :)

2020-11-20 14:51 UTC, moorscode commented on README.md
> +
```suggestion
```

2020-11-24 12:25 UTC, moorscode approved these changes

2020-11-24 12:25 UTC, merged

2020-11-24 12:25 UTC, moorscode commented
:+1: